# Generated by Django 4.2.4 on 2024-12-04 08:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_remove_todoo_deu_date_todoo_due_date_todoo_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoo',
            name='tag',
            field=models.CharField(default=django.utils.timezone.now, max_length=25),
            preserve_default=False,
        ),
    ]
